Repository CodeitPart4Team4/sb01-otboo-team04, pull requests merged in 2025-07, with the labels that each got.

#15 ✨Feature/weather #13
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/codeit/otboo/OtbooApplication.java
  src/main/java/com/codeit/otboo/domain/weather/component/KmaApiClient.java
  src/main/java/com/codeit/otboo/domain/weather/component/LocationConverter.java
  src/main/java/com/codeit/otboo/domain/weather/component/WeatherParser.java
  src/main/java/com/codeit/otboo/domain/weather/controller/WeatherController.java
  src/main/java/com/codeit/otboo/domain/weather/dto/KmaWeatherResponse.java
  src/main/java/com/codeit/otboo/domain/weather/dto/WeatherCreateRequest.java
  src/main/java/com/codeit/otboo/domain/weather/dto/WeatherDto.java
  src/main/java/com/codeit/otboo/domain/weather/dto/WeatherResponse.java
  src/main/java/com/codeit/otboo/domain/weather/entity/Weather.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/HumidityInfo.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/LocationInfo.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/PrecipitationInfo.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/PrecipitationType.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/SkyStatus.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/TemperatureInfo.java
  src/main/java/com/codeit/otboo/domain/weather/entity/vo/WindSpeedInfo.java
  src/main/java/com/codeit/otboo/domain/weather/repository/WeatherRepository.java
  src/main/java/com/codeit/otboo/domain/weather/service/WeatherService.java
  src/main/java/com/codeit/otboo/domain/weather/service/WeatherServiceImpl.java
  src/main/java/com/codeit/otboo/global/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ 새 기능 추가

#10 Feature/follow #4
  build.gradle
  src/main/java/com/codeit/otboo/domain/dm/dto/DmDto.java
  src/main/java/com/codeit/otboo/domain/dm/entity/Dm.java
  src/main/java/com/codeit/otboo/domain/follow/controller/FollowController.java
  src/main/java/com/codeit/otboo/domain/follow/dto/FollowCreateRequest.java
  src/main/java/com/codeit/otboo/domain/follow/dto/FollowDto.java
  src/main/java/com/codeit/otboo/domain/follow/dto/FollowListResponse.java
  src/main/java/com/codeit/otboo/domain/follow/dto/FollowSummaryDto.java
  src/main/java/com/codeit/otboo/domain/follow/dto/UserSummary.java
  src/main/java/com/codeit/otboo/domain/follow/entity/Follow.java
  src/main/java/com/codeit/otboo/domain/follow/mapper/FollowMapper.java
  src/main/java/com/codeit/otboo/domain/follow/repository/FollowRepository.java
  src/main/java/com/codeit/otboo/domain/follow/service/FollowService.java
  src/main/java/com/codeit/otboo/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/codeit/otboo/domain/notification/entity/Notification.java
  src/main/java/com/codeit/otboo/global/config/SecurityConfig.java
  src/main/java/com/codeit/otboo/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ 새 기능 추가

#12 :sparkles: Feature/ci action #003
  .github/workflows/ci-action.yml
Labels: ✨ 새 기능 추가

#58 Feature/profile location #57
  src/main/java/com/codeit/otboo/domain/location/api/KakaoLocalApiService.java
  src/main/java/com/codeit/otboo/domain/location/controller/LocationController.java
  src/main/java/com/codeit/otboo/domain/location/dto/KakaoRegionDto.java
  src/main/java/com/codeit/otboo/domain/location/dto/response/KakaoRegionResponse.java
  src/main/java/com/codeit/otboo/domain/location/dto/response/LocationResponse.java
  src/main/java/com/codeit/otboo/domain/location/service/LocationService.java
  src/main/java/com/codeit/otboo/domain/location/util/GridCoordinateConverter.java
  src/main/java/com/codeit/otboo/domain/location/vo/GridCoordinate.java
  src/main/java/com/codeit/otboo/domain/user/dto/request/ProfileUpdateRequest.java
  src/main/java/com/codeit/otboo/domain/user/entity/Profile.java
  src/main/java/com/codeit/otboo/domain/user/mapper/ProfileMapper.java
  src/main/java/com/codeit/otboo/domain/user/service/UserService.java
  src/main/java/com/codeit/otboo/domain/weather/batch/WeatherBatchConfig.java
  src/main/java/com/codeit/otboo/domain/weather/component/WeatherParser.java
  src/main/java/com/codeit/otboo/domain/weather/controller/WeatherController.java
  src/main/java/com/codeit/otboo/domain/weather/dto/DailySummaryDto.java
  src/main/java/com/codeit/otboo/domain/weather/dto/WeatherDto.java
  src/main/java/com/codeit/otboo/domain/weather/entity/Weather.java
  src/main/java/com/codeit/otboo/domain/weather/service/WeatherService.java
  src/main/java/com/codeit/otboo/domain/weather/service/WeatherServiceImpl.java
  src/main/java/com/codeit/otboo/global/config/WebConfig.java
  src/main/java/com/codeit/otboo/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: ✨ 새 기능 추가, 🐛버그 수정

#63 Fix/feed #62
  src/main/java/com/codeit/otboo/domain/feed/dto/response/CommentDtoCursorResponse.java
  src/main/java/com/codeit/otboo/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/otboo/domain/feed/entity/Feed.java
  src/main/java/com/codeit/otboo/domain/feed/entity/FeedComment.java
  src/main/java/com/codeit/otboo/domain/feed/entity/FeedLike.java
  src/main/java/com/codeit/otboo/domain/feed/entity/Ootd.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedCommentRepository.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedCommentRepositoryCustom.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedCommentRepositoryImpl.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedRepository.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/com/codeit/otboo/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/com/codeit/otboo/domain/feed/service/impl/CommentServiceImpl.java
  src/main/java/com/codeit/otboo/domain/feed/service/impl/FeedLikeServiceImpl.java
  src/main/java/com/codeit/otboo/domain/feed/service/impl/FeedServiceImpl.java
  src/main/resources/schema.sql
  src/test/resources/application-test.yml
Labels: 🐛버그 수정

#76 feat: 날씨 변화 알림 기능 구현
  build.gradle
  src/main/java/com/codeit/otboo/domain/notification/service/WeatherAlertService.java
  src/main/java/com/codeit/otboo/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/otboo/domain/weather/batch/WeatherBatchConfig.java
  src/main/resources/application.yml
  src/test/java/com/codeit/otboo/domain/notification/service/WeatherAlertServiceTest.java
Labels: ✨ 새 기능 추가

#77 Hotfix/dm #75
  build.gradle
  src/main/java/com/codeit/otboo/domain/clothes/service/AdminClothesService.java
  src/main/java/com/codeit/otboo/domain/dm/controller/DmController.java
  src/main/java/com/codeit/otboo/domain/dm/controller/DmWebSocketController.java
  src/main/java/com/codeit/otboo/domain/dm/redis/RedisPublisher.java
  src/main/java/com/codeit/otboo/domain/dm/redis/RedisSubscriber.java
  src/main/java/com/codeit/otboo/domain/dm/repository/DmRepository.java
  src/main/java/com/codeit/otboo/domain/dm/service/DmService.java
  src/main/java/com/codeit/otboo/domain/dm/service/DmServiceImpl.java
  src/main/java/com/codeit/otboo/domain/dm/util/DmKeyUtil.java
  src/main/java/com/codeit/otboo/domain/dm/websocket/DmWebSocketController.java
  src/main/java/com/codeit/otboo/domain/dm/websocket/NewDmEvent.java
  src/main/java/com/codeit/otboo/domain/dm/websocket/WebSocketAuthInterceptor.java
  src/main/java/com/codeit/otboo/domain/dm/websocket/WebsocketHandler.java
  src/main/java/com/codeit/otboo/domain/feed/service/impl/CommentServiceImpl.java
  src/main/java/com/codeit/otboo/domain/feed/service/impl/FeedLikeServiceImpl.java
  src/main/java/com/codeit/otboo/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/otboo/domain/follow/repository/FollowRepository.java
  src/main/java/com/codeit/otboo/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/codeit/otboo/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/otboo/domain/user/service/UserService.java
  src/main/java/com/codeit/otboo/global/config/RedisConfig.java
  src/main/java/com/codeit/otboo/global/config/RoleHierarchyConfig.java
  src/main/java/com/codeit/otboo/global/config/SecurityConfig.java
  src/main/java/com/codeit/otboo/global/config/WebSocketBrokerConfig.java
  src/main/java/com/codeit/otboo/global/error/ErrorCode.java
Labels: 🐛버그 수정

#80 Test/notification,follow
  src/main/java/com/codeit/otboo/domain/follow/entity/Follow.java
  src/main/java/com/codeit/otboo/domain/follow/repository/FollowRepository.java
  src/main/java/com/codeit/otboo/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/codeit/otboo/domain/notification/controller/NotificationController.java
  src/main/java/com/codeit/otboo/domain/notification/entity/Notification.java
  src/main/java/com/codeit/otboo/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/codeit/otboo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/otboo/domain/notification/service/NotificationServiceImpl.java
  src/test/java/com/codeit/otboo/OtbooApplicationTests.java
  src/test/java/com/codeit/otboo/domain/TestApplication.java
  src/test/java/com/codeit/otboo/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/codeit/otboo/domain/follow/mapper/FollowMapperTest.java
  src/test/java/com/codeit/otboo/domain/follow/repository/FollowRepositoryTest.java
  src/test/java/com/codeit/otboo/domain/follow/service/FollowServiceImplTest.java
  src/test/java/com/codeit/otboo/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/otboo/domain/notification/mapper/NotificationMapperTest.java
  src/test/java/com/codeit/otboo/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/codeit/otboo/domain/notification/service/NotificationServiceImplTest.java
  src/test/resources/application-test.yml
Labels: ✅테스트 코드 작업

#84 test(weather): 날씨 기능 단위/통합 테스트 코드 작성
  build.gradle
  src/main/java/com/codeit/otboo/domain/weather/batch/WeatherBatchConfig.java
  src/main/java/com/codeit/otboo/domain/weather/repository/WeatherRepository.java
  src/main/java/com/codeit/otboo/global/config/QueryDslConfig.java
  src/test/java/com/codeit/otboo/domain/TestApplication.java
  src/test/java/com/codeit/otboo/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/codeit/otboo/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/otboo/domain/weather/batch/WeatherBatchIntegrationTest.java
  src/test/java/com/codeit/otboo/domain/weather/batch/WeatherItemProcessorTest.java
  src/test/java/com/codeit/otboo/domain/weather/component/WeatherParserTest.java
  src/test/java/com/codeit/otboo/domain/weather/controller/WeatherControllerTest.java
  src/test/java/com/codeit/otboo/domain/weather/service/WeatherServiceImplTest.java
  src/test/resources/application-test.yml
  src/test/resources/schema.sql
Labels: ✅테스트 코드 작업

#94 chore(build): JaCoCo 테스트 커버리지 리포트 제외 설정 수정
  build.gradle
Labels: 📝문서 작업

#103 feat(weather): 오래된 날씨 데이터 자동 삭제 및 조회 로직 개선
  src/main/java/com/codeit/otboo/domain/weather/batch/BatchController.java
  src/main/java/com/codeit/otboo/domain/weather/batch/WeatherBatchConfig.java
  src/main/java/com/codeit/otboo/domain/weather/entity/Weather.java
  src/main/java/com/codeit/otboo/domain/weather/repository/WeatherRepository.java
  src/main/java/com/codeit/otboo/domain/weather/scheduler/WeatherDataCleanupService.java
  src/main/java/com/codeit/otboo/domain/weather/service/WeatherServiceImpl.java
  src/main/java/com/codeit/otboo/global/config/SecurityConfig.java
  src/test/java/com/codeit/otboo/domain/weather/batch/WeatherItemProcessorTest.java
  src/test/java/com/codeit/otboo/domain/weather/service/WeatherServiceImplTest.java
Labels: ✨ 새 기능 추가
